version: '3'
services:
# Telemetry MS
  telemetry:
    build: ./xpto-tracking-telemetry-ms
    ports:
        - 8080:8080
    environment:
        - spring.datasource.url=jdbc:postgresql://172.17.0.1:5960/xptotracking_ms_telemetry?currentSchema=public
        - spring.datasource.username=postgres
        - spring.datasource.password=postgres
    depends_on:
        - telemetry_pg
# Telemtry DB
  telemetry_pg:
    image: postgres:13
    ports:
        - 5960:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=xptotracking_ms_telemetry
# Vehicle MS
  vehicle:
    build: ./xpto-tracking-vehicle-ms
    ports:
        - 8081:8080
    environment:
        - spring.datasource.url=jdbc:postgresql://172.17.0.1:5961/xptotracking_ms_vehicle?currentSchema=public
        - spring.datasource.username=postgres
        - spring.datasource.password=postgres
        - client.integration.tracking.telemetry-profile.base-path=http://172.17.0.1:8080/tracking
        - client.integration.tracking.driver.base-path=http://172.17.0.1:8082/tracking
    depends_on:
        - vehicle_pg
        - telemetry
        - people
# Vehicle DB
  vehicle_pg:
    image: postgres:13
    ports:
        - 5961:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=xptotracking_ms_vehicle
# People MS
  people:
    build: ./xpto-tracking-people-ms
    ports:
        - 8082:8080
    environment:
        - DATABASE_URI=postgresql://postgres:postgres@172.17.0.1:5962/xptotracking_ms_people
    depends_on:
        - people_pg
# People DB
  people_pg:
    image: postgres:13
    ports:
        - 5962:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=xptotracking_ms_people
# Data MS
  data:
    build: ./xpto-tracking-data-ms
    ports:
        - 8083:8080
    environment:
        - DATABASE_URI=postgresql://postgres:postgres@172.17.0.1:5963/xptotracking_ms_data
        - VEHICLE_API_URI=http://172.17.0.1:8081/tracking
    depends_on:
        - data_pg
        - vehicle
# Data DB
  data_pg:
    image: postgres:13
    ports:
        - 5963:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=xptotracking_ms_data