# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class CreateGeoDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, geo_data_id: str=None):  # noqa: E501
        """CreateGeoDataResponse - a model defined in Swagger

        :param geo_data_id: The geo_data_id of this CreateGeoDataResponse.  # noqa: E501
        :type geo_data_id: str
        """
        self.swagger_types = {
            'geo_data_id': str
        }

        self.attribute_map = {
            'geo_data_id': 'geoDataId'
        }
        self._geo_data_id = geo_data_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateGeoDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateGeoDataResponse of this CreateGeoDataResponse.  # noqa: E501
        :rtype: CreateGeoDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def geo_data_id(self) -> str:
        """Gets the geo_data_id of this CreateGeoDataResponse.


        :return: The geo_data_id of this CreateGeoDataResponse.
        :rtype: str
        """
        return self._geo_data_id

    @geo_data_id.setter
    def geo_data_id(self, geo_data_id: str):
        """Sets the geo_data_id of this CreateGeoDataResponse.


        :param geo_data_id: The geo_data_id of this CreateGeoDataResponse.
        :type geo_data_id: str
        """
        if geo_data_id is None:
            raise ValueError("Invalid value for `geo_data_id`, must not be `None`")  # noqa: E501

        self._geo_data_id = geo_data_id
