# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class CreateTelemetryDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, telemetry_data_id: str=None):  # noqa: E501
        """CreateTelemetryDataResponse - a model defined in Swagger

        :param telemetry_data_id: The telemetry_data_id of this CreateTelemetryDataResponse.  # noqa: E501
        :type telemetry_data_id: str
        """
        self.swagger_types = {
            'telemetry_data_id': str
        }

        self.attribute_map = {
            'telemetry_data_id': 'telemetryDataId'
        }
        self._telemetry_data_id = telemetry_data_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateTelemetryDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateTelemetryDataResponse of this CreateTelemetryDataResponse.  # noqa: E501
        :rtype: CreateTelemetryDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def telemetry_data_id(self) -> str:
        """Gets the telemetry_data_id of this CreateTelemetryDataResponse.


        :return: The telemetry_data_id of this CreateTelemetryDataResponse.
        :rtype: str
        """
        return self._telemetry_data_id

    @telemetry_data_id.setter
    def telemetry_data_id(self, telemetry_data_id: str):
        """Sets the telemetry_data_id of this CreateTelemetryDataResponse.


        :param telemetry_data_id: The telemetry_data_id of this CreateTelemetryDataResponse.
        :type telemetry_data_id: str
        """
        if telemetry_data_id is None:
            raise ValueError("Invalid value for `telemetry_data_id`, must not be `None`")  # noqa: E501

        self._telemetry_data_id = telemetry_data_id
