# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.enum_sensor_type import EnumSensorType  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class CreateTelemetryDataRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vehicle_id: str=None, _date: datetime=None, sensor_type: EnumSensorType=None, value: str=None):  # noqa: E501
        """CreateTelemetryDataRequest - a model defined in Swagger

        :param vehicle_id: The vehicle_id of this CreateTelemetryDataRequest.  # noqa: E501
        :type vehicle_id: str
        :param _date: The _date of this CreateTelemetryDataRequest.  # noqa: E501
        :type _date: datetime
        :param sensor_type: The sensor_type of this CreateTelemetryDataRequest.  # noqa: E501
        :type sensor_type: EnumSensorType
        :param value: The value of this CreateTelemetryDataRequest.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'vehicle_id': str,
            '_date': datetime,
            'sensor_type': EnumSensorType,
            'value': str
        }

        self.attribute_map = {
            'vehicle_id': 'vehicleId',
            '_date': 'date',
            'sensor_type': 'sensor_type',
            'value': 'value'
        }
        self._vehicle_id = vehicle_id
        self.__date = _date
        self._sensor_type = sensor_type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'CreateTelemetryDataRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateTelemetryDataRequest of this CreateTelemetryDataRequest.  # noqa: E501
        :rtype: CreateTelemetryDataRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vehicle_id(self) -> str:
        """Gets the vehicle_id of this CreateTelemetryDataRequest.


        :return: The vehicle_id of this CreateTelemetryDataRequest.
        :rtype: str
        """
        return self._vehicle_id

    @vehicle_id.setter
    def vehicle_id(self, vehicle_id: str):
        """Sets the vehicle_id of this CreateTelemetryDataRequest.


        :param vehicle_id: The vehicle_id of this CreateTelemetryDataRequest.
        :type vehicle_id: str
        """
        if vehicle_id is None:
            raise ValueError("Invalid value for `vehicle_id`, must not be `None`")  # noqa: E501

        self._vehicle_id = vehicle_id

    @property
    def _date(self) -> datetime:
        """Gets the _date of this CreateTelemetryDataRequest.

        Creation date and time  # noqa: E501

        :return: The _date of this CreateTelemetryDataRequest.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this CreateTelemetryDataRequest.

        Creation date and time  # noqa: E501

        :param _date: The _date of this CreateTelemetryDataRequest.
        :type _date: datetime
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def sensor_type(self) -> EnumSensorType:
        """Gets the sensor_type of this CreateTelemetryDataRequest.


        :return: The sensor_type of this CreateTelemetryDataRequest.
        :rtype: EnumSensorType
        """
        return self._sensor_type

    @sensor_type.setter
    def sensor_type(self, sensor_type: EnumSensorType):
        """Sets the sensor_type of this CreateTelemetryDataRequest.


        :param sensor_type: The sensor_type of this CreateTelemetryDataRequest.
        :type sensor_type: EnumSensorType
        """
        if sensor_type is None:
            raise ValueError("Invalid value for `sensor_type`, must not be `None`")  # noqa: E501

        self._sensor_type = sensor_type

    @property
    def value(self) -> str:
        """Gets the value of this CreateTelemetryDataRequest.

        Value  # noqa: E501

        :return: The value of this CreateTelemetryDataRequest.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this CreateTelemetryDataRequest.

        Value  # noqa: E501

        :param value: The value of this CreateTelemetryDataRequest.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
